# name: Deploy to GCP Compute Engine

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Install SSH key
#       uses: webfactory/ssh-agent@v0.5.3
#       with:
#         ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

#     - name: Stop running Python program
#       run: |
#         ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_VM_IP }} "pkill -f python3"

#     - name: Pull latest code
#       run: |
#         ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_VM_IP }} "cd /path/to/your/repo && git pull"

#     - name: Reboot system
#       run: |
#         ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_VM_IP }} "sudo reboot"
